### ISSUE TITLE
Installed, ChestCommands4.04 and ItemsAdder2.5.1, neither of them work

### ISSUE THREAD

**Issue by StealthDeci** [LoneDev6/ChestCommands#5]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

Installed, ChestCommands4.04 and ItemsAdder2.5.1, neither of them work

### How to reproduce

Installed, ChestCommands4.04 and ItemsAdder2.5.1, neither of them work

### Server version

1.18.1 PurPur

### Chest Commands version

4.0.4

### Additional information

Installed, ChestCommands4.04 and ItemsAdder2.5.1, neither of them work

**Comment by LoneDev6** [comment]
Duplicate https://github.com/PluginBugs/Issues-ItemsAdder/issues/1381
