### ISSUE TITLE
Fatal unexpected error while enabling plugin

### ISSUE THREAD

**Issue by doduk7777** [LoneDev6/ChestCommands#6]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

**Thank you for your hard work.** I found an error that did not work while running the plugin. We will notify you of the problem in a log file.

### How to reproduce

1. After installing the plug-in, run the server.
2. Wait for the running server.
3. Check the server log for a problem 

[ChestCommands] Fatal unexpected error while enabling plugin:

### Server version

1.19.2

### Chest Commands version

chestcommands-plugin-4.0.4-SNAPSHOT-unofficial

### Additional information

[latest.log](https://github.com/LoneDev6/ChestCommands-ItemsAdder/files/9333508/latest.log)

**Comment by LoneDev6** [comment]
Install ItemsAdder.
